FROM quay.io/fedora/fedora-silverblue:latest

COPY --chown=root:root --chmod=644 files/policy.json /etc/containers/policy.json
COPY --chown=root:root --chmod=644 files/ghcr.io.yaml /etc/containers/registries.d/ghcr.io.yaml

RUN sed --in-place 's/enabled = no/enabled = true/' \
	/usr/lib/ostree/prepare-root.conf && \
	echo -e 'fastestmirror=True\nmax_parallel_downloads=8' >> /etc/dnf/dnf.conf && \
	echo -e '[mullvad]\nname=Mullvad VPN\nbaseurl=https://repository.mullvad.net/rpm/stable/$basearch\ntype=rpm\nenabled=1\ngpgcheck=1\ngpgkey=https://repository.mullvad.net/rpm/mullvad-keyring.asc' | tee /etc/yum.repos.d/mullvad.repo > /dev/null && \
	echo -e '[tailscale]\nname=Tailscale\nbaseurl=https://pkgs.tailscale.com/stable/fedora/$basearch\nenabled=1\ntype=rpm\ngpgcheck=1\ngpgkey=https://pkgs.tailscale.com/stable/fedora/repo.gpg' | tee /etc/yum.repos.d/tailscale.repo > /dev/null && \
	echo -e '[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc' | tee /etc/yum.repos.d/vscode.repo > /dev/null

RUN dnf --assumeyes install \
	# GUI
	breeze-cursor-theme \
	mullvad-browser \
	# mullvad-vpn \
	profile-sync-daemon \
	# CLI
	distrobox \
	dua-cli \
	helix \
	htop \
	iotop-c \
	nvtop \
	papirus-icon-theme \
	tailscale \
	xonsh \
	# Devel
	code \
	podman-compose \
	podman-docker \
	podman-tui \
	# Fonts
	cascadia-fonts-all \
	default-fonts \
	liberation-fonts-all \
	# Gnome
	gnome-shell-extension-appindicator \
	gnome-shell-extension-argos \
	gnome-shell-extension-caffeine \
	gnome-shell-extension-gsconnect \
	# Cleanup
	&& dnf --assumeyes remove \
	firefox \
	&& dnf clean all && \
	systemctl enable tailscaled && \
	rm -frv /var/* && \
	ostree container commit

RUN bootc container lint
