FROM quay.io/fedora/fedora-silverblue:latest

COPY --chown=root:root --chmod=644 \
	files/tailscale.gpg files/tailscale.repo \
	files/vscode.gpg files/vscode.repo \
	/tmp/
COPY --chown=root:root --chmod=644 files/policy.json /etc/containers/policy.json
COPY --chown=root:root --chmod=644 files/ghcr.io.yaml /etc/containers/registries.d/ghcr.io.yaml

RUN sed --in-place 's/enabled = no/enabled = yes/' \
	/usr/lib/ostree/prepare-root.conf && \
	rpm --import /tmp/tailscale.gpg /tmp/vscode.gpg && \
	dnf config-manager addrepo --from-repofile=/tmp/tailscale.repo && \
	dnf config-manager addrepo --from-repofile=/tmp/vscode.repo && \
	rm -f /tmp/tailscale.gpg /tmp/tailscale.repo /tmp/vscode.gpg /tmp/vscode.repo

RUN dnf --assumeyes install \
	# CLI
	dua-cli \
	helix \
	htop \
	iotop-c \
	nvtop \
	papirus-icon-theme \
	profile-sync-daemon \
	tailscale \
	xonsh \
	# Devel
	code \
	podman-compose \
	podman-docker \
	podman-tui \
	# Fonts
	cascadia-fonts-all \
	default-fonts \
	jetbrains-mono-fonts-all \
	liberation-fonts-all \
	# Gnome
	gnome-shell-extension-appindicator \
	gnome-shell-extension-argos \
	gnome-shell-extension-caffeine \
	gnome-shell-extension-gsconnect \
	# Cleanup
	&& dnf clean all && \
	systemctl enable tailscaled && \
	ostree container commit

RUN bootc container lint
