FROM quay.io/toolbx/ubuntu-toolbox:latest

LABEL name="spotify-box"

ENV DEBIAN_FRONTEND=noninteractive

COPY --chown=root:root --chmod=644 files/spotify.gpg /etc/apt/trusted.gpg.d/spotify.gpg
COPY --chown=root:root --chmod=644 files/spotify.list /etc/apt/sources.list.d/spotify.list

RUN apt-get update && \
    apt-get --assume-yes install \
    pipewire \
    spotify-client \
    && apt-get distclean

VOLUME /var/home