FROM quay.io/toolbx/arch-toolbox:latest

LABEL name="steam-box"

RUN pacman -Syu --noconfirm \
    lib32-vulkan-mesa-layers \
    lib32-vulkan-radeon \
    lib32-mangohud \
    pipewire-alsa \
    pipewire-pulse \
    steam \
    ttf-liberation \
    xdg-desktop-portal-gnome \
    && pacman -Sc --noconfirm

VOLUME /steam /var/home
