FROM quay.io/toolbx/arch-toolbox:latest

LABEL name="comfy-box"

RUN pacman -Syu --noconfirm \
    python-pytorch-opt-rocm \
    python-torchvision \
    && pacman -Sc --noconfirm
RUN git clone https://github.com/comfyanonymous/ComfyUI.git /comfy

VOLUME /comfy/models /comfy/output /var/home
